version: 2.1
orbs:
  elixir: coletiv/elixir@0.0.1
jobs:
  build-and-test:
    executor: elixir/default
    steps:
      - elixir/build
      - elixir/check-format
      - elixir/coveralls
      - elixir/credo
      - elixir/dialyzer
      
workflows:
  elixir-build-deploy-example:
    jobs:
      - my-orb/build:
          name: mybuild # best practice is to name each orb job
      - my-orb/deploy:
          branch: master
          requires:
            - mybuild
          filters:
            branches:
              only: master
      - my-orb/deploy:
          branch: new
          requires:
            - mybuild
          filters:
            branches:
              only: new
