version: 2.1
orbs:
  elixir: coletiv/elixir@0.0.1
jobs:
  build-and-test:
    executor: elixir/default
    steps:
      - elixir/build
      - elixir/check-format
      - elixir/coveralls
      - elixir/credo
      - elixir/dialyzer
  deploy:
    executor: elixir/default
    parameters:
      branch:
        type: string
    steps:
      - run: |
          echo "Branch: << parameters.branch >>"
workflows:
  elixir-build-deploy-example:
    jobs:
      - build-and-test
      - deploy:
          branch: develop
          filters:
            branches:
              only: develop
      - deploy:
          branch: master
          filters:
            branches:
              only: master
